#ifndef VOXEL_BLOCK_TYPE_H
#define VOXEL_BLOCK_TYPE_H
enum VOXEL_BLOCK_TYPE_ENUM
{
    BLOCK_VOID,
    BLOCK_AIR,
    BLOCK_GRASS,
    BLOCK_DIRT,
    BLOCK_COBBLE,
    BLOCK_LOG,
    BLOCK_LEAF,
    BLOCK_PLANKS
} voxel_block_type;
#endif
